export const browserCoreExamples = [
  "cryptoclaw browser status",
  "cryptoclaw browser start",
  "cryptoclaw browser stop",
  "cryptoclaw browser tabs",
  "cryptoclaw browser open https://example.com",
  "cryptoclaw browser focus abcd1234",
  "cryptoclaw browser close abcd1234",
  "cryptoclaw browser screenshot",
  "cryptoclaw browser screenshot --full-page",
  "cryptoclaw browser screenshot --ref 12",
  "cryptoclaw browser snapshot",
  "cryptoclaw browser snapshot --format aria --limit 200",
  "cryptoclaw browser snapshot --efficient",
  "cryptoclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "cryptoclaw browser navigate https://example.com",
  "cryptoclaw browser resize 1280 720",
  "cryptoclaw browser click 12 --double",
  'cryptoclaw browser type 23 "hello" --submit',
  "cryptoclaw browser press Enter",
  "cryptoclaw browser hover 44",
  "cryptoclaw browser drag 10 11",
  "cryptoclaw browser select 9 OptionA OptionB",
  "cryptoclaw browser upload /tmp/file.pdf",
  'cryptoclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "cryptoclaw browser dialog --accept",
  'cryptoclaw browser wait --text "Done"',
  "cryptoclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "cryptoclaw browser console --level error",
  "cryptoclaw browser pdf",
];
